name: scalaproject
description: ''
version: 0.0.1
author: g.ayush@prophecy.io
language: scala
buildSystem: ''
buildSystemDetails:
  artefactID: scalaproject
  parentArtefactID: gayushprophecyioteam
  buildSystem: maven
  author: null
  createdAt: '2026-01-19 11:22:53'
pipelines:
  pipelines/p1:
    name: p1
    description: ''
    author: g.ayush@prophecy.io
    mode: batch
    artefactID: ''
    language: scala
    createdAt: '2026-01-19 11:22:53'
    datasets:
      inputs:
      - datasets/ds
      outputs: []
    subgraphs: []
    dependencies: {}
datasets:
  datasets/ds:
    name: ds
    description: ''
    author: g.ayush@prophecy.io
    createdAt: '2026-01-19 11:25:00'
    mode: batch
    physicalDatasets:
      guides-prod-fabric:
        fabricId: 30674
        datasetType: File
        description: ''
        author: g.ayush@prophecy.io
        createdAt: '2026-01-19 11:25:00'
templates: {}
jobs: {}
gemContainer:
  languageVersion: 2.12.15
  gemLibsVersion: 1.1.26
  gems: {}
  dependencies: null
functions:
  author: null
  createdAt: '2026-01-19 11:22:53'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
  businessRules: {}
subgraphs: {}
sqlModels: {}
sqlSnapshots: {}
sqlTests: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies:
- modifiedAt: '2026-01-19T11:22:53.822734Z'
  name: plibMaven
  version: 8.16.0
  id: '1533673390'
  createdAt: '2026-01-19T11:22:53.822734Z'
  type: plibMaven
projectDependencies:
  '12651':
    projectUID: 12651
    projectName: ProphecySparkBasicsScala
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12651.git&subPath=
    version: 0.2.6.6
    isDefault: true
    author: null
    createdAt: '2026-01-19 11:22:37'
  '12652':
    projectUID: 12652
    projectName: ProphecyWarehouseScala
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12652.git&subPath=
    version: 0.0.6
    isDefault: true
    author: null
    createdAt: '2026-01-19 11:22:37'
flags:
  shouldAddDefaultDependenciesIfAbsent: true
pipelineConfigurations: {}
projectConfigurations: {}
